version: "3.8"
services:
  crac_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports: 
      - 3030:3030
    network_mode: host
    command: "-m"
  crac_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment: 
      DISPLAY: 192.168.0.34:0
    network_mode: host
    depends_on:
      - "crac_server"
  