version: "3.8"
services:
  crac_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - .:/crac
    ports: 
      - 3030:3030
    network_mode: host
    command: "-m"
  crac_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - .:/crac
    environment: 
      DISPLAY: ${DISPLAY}
    network_mode: host
    depends_on:
      - "crac_server"
  