class GuiLabel:

    NO_ALERT = "Nessun errore riscontrato"
    ALERT_THE_SKY_LOST = "Connessione con the Sky persa"
    ALERT_THE_SKY_ERROR = "Errore di TheSky"
    ALERT_CHECK_CURTAINS_SWITCH = "Controllare switch tende - ricalibrazione"
    ALERT_CRAC_ANOMALY = "Anomalia CRaC: stato invalido dei componenti"
    ALERT_TELESCOPE_ROOF = "Attenzione, Telescopio vicino al tetto"
    ALERT_TELESCOPE_ROOF_CLOSING = "Attenzione, Telescopio non in park e tetto in chiusura"
    ALERT_TELESCOPE_OPERATIVE = "Attenzione telescopio operativo: {status}"
    ALERT_CURTAINS_OPEN = "Attenzione tende aperte"
    ALERT_ROOF_CLOSED = "Attenzione tetto chiuso"
    CURTAINS_CLOSED = "Disattive"
    CURTAINS_OPEN = "Attive"
    CURTAINS_ANOMALY = "Anomalia"
    TELESCOPE_PARKED = "Parked"
    TELESCOPE_FLATTER = "Flatter"
    TELESCOPE_SECURED = "In Sicurezza"
    TELESCOPE_NE = "NordEst"
    TELESCOPE_EE = "Est"
    TELESCOPE_SE = "SudEst"
    TELESCOPE_SW = "SudOvest"
    TELESCOPE_WW = "Ovest"
    TELESCOPE_NW = "NordOvest"
    TELESCOPE_ANOMALY = "Anomalia"
    TELESCOPE_ERROR = "Errore"
    TELESCOPE_TRACKING_ON = "Track On"
    TELESCOPE_TRACKING_OFF = "Track Off"
    ROOF_CLOSED = "Chiuso"
    ROOF_OPEN = "Aperto"
    PANEL_ON = "Acceso"
    PANEL_OFF = "Spento"


class GuiKey:

    OPEN_ROOF = "R"
    PARK_TELE = "P"
    FLAT_TELE = "F"
    CLOSE_ROOF = "T"
    START_CURTAINS = "1"
    STOP_CURTAINS = "0"
    CALIBRATE_CURTAINS = "2"
    SHUTDOWN = "-"
    CONTINUE = "c"
    EXIT = "E"
    TIMEOUT = "__TIMEOUT__"
    PANEL_ON = "L"
    PANEL_OFF = "D"
    LIGHT_ON = "K"
    LIGHT_OFF = "J"
    POWER_ON = "W"
    POWER_OFF = "X"
    AUX_ON = "A"
    AUX_OFF = "O"
