class GuiLabel:

    NO_ALERT = "Nessun errore riscontrato"
    ALERT_THE_SKY_LOST = "Connessione con the Sky persa"
    ALERT_THE_SKY_ERROR = "Errore di TheSky"
    ALERT_CHECK_CURTAINS_SWITCH = "Controllare switch tende - ricalibrazione"
    ALERT_CRAC_ANOMALY = "Anomalia CRaC: stato invalido dei componenti"
    ALERT_TELESCOPE_ROOF = "Attenzione, Telescopio vicino al tetto"
    ALERT_TELESCOPE_ROOF_CLOSING = "Attenzione, Telescopio non in park e tetto in chiusura"
    ALERT_TELESCOPE_OPERATIVE = "Attenzione telescopio operativo"
    ALERT_CURTAINS_ACTIVED = "Attenzione tende aperte"
    ALERT_ROOF_CLOSED = "Attenzione tetto chiuso"
    CURTAINS_DEACTIVED = "Disattive"
    CURTAINS_ACTIVED = "Attive"
    CURTAINS_ANOMALY = "Anomalia"
    TELESCOPE_PARKED = "Parked"
    TELESCOPE_FLATTER = "Flatter"
    TELESCOPE_SECURED = "In Sicurezza"
    TELESCOPE_OPERATIVE = "Operativo"
    TELESCOPE_ANOMALY = "Anomalia"
    TELESCOPE_ERROR = "Errore"
    TELESCOPE_TRACKING_ON = "Track On"
    TELESCOPE_TRACKING_OFF = "Track Off"
    ROOF_CLOSED = "Chiuso"
    ROOF_OPEN = "Aperto"
    PANEL_ON = "Acceso"
    PANEL_OFF = "Spento"

class GuiKey:

    OPEN_ROOF = "R"
    PARK_TELE = "P"
    FLAT_TELE = "F"
    CLOSE_ROOF = "T"
    ACTIVED_CURTAINS = "1"
    DEACTIVED_CURTAINS = "0"
    CALIBRATE_CURTAINS = "2"
    SHUTDOWN = "-"
    CONTINUE = "c"
    EXIT = "E"
    TIMEOUT = "__TIMEOUT__"
    PANEL_ON = "L"
    PANEL_OFF = "D"
